eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/,http://127.0.0.1:8200/eureka/,http://127.0.0.1:8300/eureka/  #注册中心默认地址

server:
  port: 8081
spring:
  application:
    name: feign
feign:
  hystrix:
    enabled: true   #开启熔断器